# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f6e8b2ee6bc59f874493237293d045b293671d3316fd9f48d0882d34181552ac46f9ec6c09089637acda10d4ef45679d9db94400906a048c0a2ae71bb116539

test:
  secret_key_base: f906e862b68e3e04ab7fdd57b20b077519fe87eb1baeb659c31ced7b1d92194538bb3d880c8c6c841d0c9b4338d455020ac6c6363bfb2ef568d8f059f8296fae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
